# Generated by Django 2.1.15 on 2020-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('enquire_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email2', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('number', models.CharField(default='', max_length=14)),
                ('desc', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='number',
        ),
    ]
