# Generated by Django 2.1.15 on 2020-07-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200720_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquire',
            old_name='email2',
            new_name='enquire_email',
        ),
    ]
